source "https://github.com/CocoaPods/Specs.git"

platform :ios, "7.0"
# ignore all warnings from all pods
inhibit_all_warnings!
#
#link_with 'mdcar-ios'
#link_with 'mdcar-iosTests'



target 'mdcar-ios' do
  pod "AFNetworking", "~> 2.5.2"
  pod "AFNetworkActivityLogger", "~> 2.0.3"
  pod "SDWebImage", "~> 3.7"
  pod "JSONModel", "~> 0.9.2"
  pod "OHHTTPStubs", "~> 3.1.5"
#  pod "pop", "~> 1.0"
  pod "Overcoat", "~> 2.0.2"
end

target 'mdcar-iosTests', :exclusive => true do
  pod "Expecta",     "~> 0.3"
end

